language: rust
sudo: true

rust:
  - nightly

before_script:
  - rustup component add rustfmt-preview

before_install:
  - sudo apt-get update
  - sudo apt-get install -y linux-tools-common linux-tools-generic linux-tools-`uname -r` linux-cloud-tools-`uname -r`
  - echo -1 | sudo tee /proc/sys/kernel/perf_event_paranoid

env:
  # - CHECK='cargo fmt --all -- --write-mode=diff'
  - CHECK='ci/check-benchmarks.sh'
  - CHECK='cargo check'

script:
  - sh -x -c "$CHECK"
