sudo: false
language: rust
rust:
  - nightly
before_script: (cargo install --verbose --root $HOME rustfmt || true)
script:
  - cd rs-backend
  - cargo fmt -- --write-mode=diff
  - cargo build --verbose
  - cargo test --verbose
cache: cargo
env:
  - PATH=$HOME/.cargo/bin:$PATH
