language: rust
sudo: false

cache: cargo

rust:
  - nightly

before_script:
  - rustup component add rustfmt-preview
  - git clone https://github.com/rust-lang-nursery/rustc-timing.git

env:
  - CHECK='cargo fmt --all -- --write-mode=diff'
  - CHECK='cargo run -p collector --bin collector -- --output-repo rustc-timing test_benchmarks'
  - CHECK='cargo check'

script:
  - sh -x -c "$CHECK"
