[package]
authors = ["Mark Simulacrum <mark.simulacrum@gmail.com>"]
name = "rustc-perf-collector"
version = "0.1.0"

[[bin]]
name = "benchmark"
path = "src/bin/benchmark.rs"

[dependencies]
env_logger = "0.4.0"
error-chain = "0.9"
flate2 = "0.2"
reqwest = "0.4.0"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
tar = "0.4"
clap = "~2.22.0"
log = "~0.3"
tempdir = "~0.3"

[dependencies.chrono]
features = ["serde"]
version = "0.3.1"
