[package]
authors = ["Mark Simulacrum <mark.simulacrum@gmail.com>"]
name = "rustc-perf-collector"
version = "0.1.0"

[[bin]]
name = "benchmark"
path = "src/bin/benchmark.rs"

[dependencies]
env_logger = "0.4.0"
error-chain = "0.9"
flate2 = "0.2"
reqwest = "0.4.0"
serde = "0.9"
serde_derive = "0.9"
serde_json = "0.9"
tar = "0.4"

[dependencies.chrono]
features = ["serde"]
version = "0.3"

[[bin]]
name = "benchmark"
path = "src/bin/benchmark.rs"

