[package]
authors = ["Mark-Simulacrum <mark.simulacrum@gmail.com>", "Nicholas Cameron <ncameron@mozilla.com>", "The rustc-perf contributors"]
name = "rustc-perf"
version = "0.1.0"

[dependencies]
env_logger = "0.4.2"
error-chain = "0.10.0"
futures = "0.1.13"
futures-cpupool = "0.1.5"
log = "0.3.6"
serde = "0.9.13"
serde_derive = "0.9.13"
serde_json = "0.9.10"

[dependencies.chrono]
features = ["serde"]
version = "0.3"

[dependencies.hyper]
git = "https://github.com/hyperium/hyper.git"
optional = false

[dev-dependencies]
lazy_static = "0.2.1"
