[workspace]
members = ["collector", "collector/benchlib", "site", "database", "intern"]
exclude = ["collector/compile-benchmarks", "rust/src"]

[profile.release.package.site]
debug = 1

[profile.release.package.collector]
debug = 1
