[package]
authors = ["Mark-Simulacrum <mark.simulacrum@gmail.com>", "Nicholas Cameron <ncameron@mozilla.com>", "The rustc-perf contributors"]
name = "site"
version = "0.1.0"

[dependencies]
env_logger = "0.5"
error-chain = "0.11.0"
futures = "0.1.13"
futures-cpupool = "0.1.5"
log = "0.4"
serde = "1"
serde_derive = "1"
serde_json = "1"
hyper = "0.11"
url = "1.5"
antidote = "1.0"
chrono = "0.4"
flate2 = "1.0.1"
rmp-serde = "0.13.7"
semver = "0.9"

[dependencies.collector]
path = "../collector"

[dependencies.rust_sysroot]
git = "https://github.com/Mark-Simulacrum/bisect-rust.git"
optional = false

[dev-dependencies]
lazy_static = "1"
pretty_assertions = "0.5"
