[package]
name = "database"
version = "0.1.0"
authors = ["Mark Rousskov <mark.simulacrum@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hashbrown = "0.7"
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1", features = ["raw_value"] }
rusqlite = { version = "0.23", features = ["bundled"] }
tokio-postgres = "0.5.4"
anyhow = "1"
async-trait = "0.1"
tokio = { version = "0.2.21", features = ["sync"] }
snap = "1"
intern = { path = "../intern" }
chrono = "0.4"
reqwest = { version = "0.10.5", features = ["blocking"] }
postgres-native-tls = "0.3"
native-tls = "0.2"
lazy_static = "1"
