[package]
name = "database"
version = "0.1.0"
authors = ["Mark Rousskov <mark.simulacrum@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hashbrown = "0.7"
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1", features = ["raw_value"] }
r2d2 = "0.8"
rusqlite = { version = "0.23", features = ["bundled"] }
anyhow = "1"
async-trait = "0.1"
tokio = { version = "0.2", features = ["macros"] }
snap = "1"
intern = { path = "../intern" }
chrono = "0.4"
