[package]
name = "database"
version = "0.1.0"
authors = ["Mark Rousskov <mark.simulacrum@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hashbrown = "0.7"
serde = "1"
serde_derive = "1"
serde_json = { version = "1", features = ["raw_value"] }
collector = { path = "../collector" }
r2d2 = "0.8"
rusqlite = { version = "0.23", features = ["bundled"] }
anyhow = "1"
async-trait = "0.1"
