[package]
name = "intern"
version = "0.1.0"
authors = ["Mark Rousskov <mark.simulacrum@gmail.com>"]
edition = "2018"

[dependencies]
bumpalo = "3.2"
parking_lot = "0.11"
arc-swap = "1.3"
hashbrown = "0.11"
lazy_static = "1"
serde = "1"
serde_derive = "1"
