name: CI
on:
  push: {}
  pull_request: {}
  schedule:
    - cron: "0 12 * * 1" # Every Monday at 12:00 UTC

env:
  AWS_ACCESS_KEY_ID: AKIA46X5W6CZBLO3VBND

jobs:
  test_and_deploy:
    name: Test and deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the source code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Test and build
        run: docker build -t rustc-perf .

      - name: Deploy to production
        uses: rust-lang/simpleinfra/github-actions/upload-docker-image@master
        with:
          image: rustc-perf
          repository: rust-rustc-perf
          region: us-west-1
          redeploy_ecs_cluster: rust-ecs-prod
          redeploy_ecs_service: rustc-perf
          aws_access_key_id: "${{ env.AWS_ACCESS_KEY_ID }}"
          aws_secret_access_key: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
        if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/deploy'

  test_benchmarks:
    strategy:
      matrix:
        BENCH_INCLUDE_EXCLUDE_OPTS: [
          "--exclude webrender-wrench,style-servo,cargo,rustc",
          "--include webrender-wrench,style-servo,cargo --exclude rustc",
        ]
        BUILD_KINDS: [
          "Check,Doc,Debug",
          "Opt",
        ]
    name: Test benchmarks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the source code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Install latest beta
        uses: actions-rs/toolchain@v1
        with:
          toolchain: beta
          override: true

      - name: Configure environment
        run: |
          sudo apt-get update
          sudo apt-get install -y linux-tools-common linux-tools-generic linux-tools-`uname -r`
          echo -1 | sudo tee /proc/sys/kernel/perf_event_paranoid

      - name: Install servo dependencies
        run: sudo apt-get install -y llvm-dev clang libx11-dev python2.7 autoconf2.13 libjemalloc-dev

      - name: Build collector
        run: cargo build -p collector

      - name: Check benchmarks
        run: sh -x -c "ci/check-benchmarks.sh"
        env:
          JEMALLOC_OVERRIDE: /usr/lib/x86_64-linux-gnu/libjemalloc.so
          BENCH_INCLUDE_EXCLUDE_OPTS: ${{ matrix.BENCH_INCLUDE_EXCLUDE_OPTS }}
          BUILD_KINDS: ${{ matrix.BUILD_KINDS }}
          SHELL: "/bin/bash"

  test_profiling:
    name: Test profiling
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout the source code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Install latest beta
        uses: actions-rs/toolchain@v1
        with:
          toolchain: beta
          override: true

      - name: Install profilers
        run: |
          sudo apt install -y valgrind
          cargo install --version 0.4.6 cargo-llvm-lines

      - name: Configure environment
        run: |
          sudo apt-get update
          sudo apt-get install -y linux-tools-common linux-tools-generic linux-tools-`uname -r`
          echo -1 | sudo tee /proc/sys/kernel/perf_event_paranoid

      - name: Build collector
        run: cargo build -p collector

      - name: Test automated triage
        run: sh -x -c "ci/check-triage-script.sh"

      - name: Check benchmarks
        run: sh -x -c "ci/check-profiling.sh"

